import { HousesProps } from "@/types";

const mockBuyHouses: HousesProps["houses"] = [
  {
    id: 20,
    title: "برج مسکونی خرید",
    address: "تهران - ولنجک - خیابان شهید باهنر",
    photos: "",
    rate: "4.9",
    discounted_price: null,
    price: 12000000000,
    tags: ["خرید", "برج", "لوکس"],
    last_updated: "2026-06-14T08:00:00.000Z",
    capacity: 5,
    location: { lat: 35.8012, lng: 51.4123 },
    categories: "apartment",
    bathrooms: 3,
    parking: 2,
    rooms: 3,
    yard_type: "none",
    num_comments: 18,
    discount_id: null,
    transaction_type: "buy",
    sellerId: 301,
    sellerName: "کمال رحیمی",
    caption: "واحد لوکس در برج مسکونی مدرن با امکانات کامل رفاهی",
    bookings: 1,
    favoriteId: null,
    isFavorite: false,
  },
  {
    id: 21,
    title: "خانه باغ فروشی",
    address: "لواسان - خیابان رضوانی",
    photos: "",
    rate: "5.0",
    discounted_price: 18000000000,
    price: 22000000000,
    tags: ["خرید", "باغ", "لواسان"],
    last_updated: "2026-06-12T07:00:00.000Z",
    capacity: 12,
    location: { lat: 35.8456, lng: 51.6234 },
    categories: "villa",
    bathrooms: 5,
    parking: 4,
    rooms: 6,
    yard_type: "garden",
    num_comments: 22,
    discount_id: 7,
    transaction_type: "buy",
    sellerId: 302,
    sellerName: "شیرین قاسمی",
    caption: "خانه باغ رویایی در لواسان با ۲۰۰۰ متر باغ و استخر",
    bookings: 0,
    favoriteId: 21,
    isFavorite: true,
  },
  {
    id: 22,
    title: "آپارتمان نوساز فروشی",
    address: "تهران - چیتگر - فاز ۵",
    photos: "",
    rate: "4.5",
    discounted_price: null,
    price: 5500000000,
    tags: ["خرید", "نوساز", "چیتگر"],
    last_updated: "2026-06-11T12:00:00.000Z",
    capacity: 4,
    location: { lat: 35.7789, lng: 51.2134 },
    categories: "apartment",
    bathrooms: 2,
    parking: 1,
    rooms: 2,
    yard_type: "none",
    num_comments: 6,
    discount_id: null,
    transaction_type: "buy",
    sellerId: 303,
    sellerName: "بهنام صادقی",
    caption: "آپارتمان نوساز در چیتگر نزدیک دریاچه چیتگر",
    bookings: 0,
    favoriteId: null,
    isFavorite: false,
  },
  {
    id: 23,
    title: "پنت‌هاوس فروشی",
    address: "تهران - زعفرانیه - کوچه گلستان",
    photos: "",
    rate: "4.8",
    discounted_price: 35000000000,
    price: 42000000000,
    tags: ["خرید", "پنت‌هاوس", "زعفرانیه"],
    last_updated: "2026-06-10T15:00:00.000Z",
    capacity: 6,
    location: { lat: 35.8123, lng: 51.4567 },
    categories: "apartment",
    bathrooms: 4,
    parking: 3,
    rooms: 4,
    yard_type: "rooftop",
    num_comments: 14,
    discount_id: 8,
    transaction_type: "buy",
    sellerId: 304,
    sellerName: "پریسا ملکی",
    caption: "پنت‌هاوس اختصاصی در زعفرانیه با تراس ۳۰۰ متری",
    bookings: 0,
    favoriteId: null,
    isFavorite: false,
  },
  {
    id: 24,
    title: "ویلای ساحلی فروشی",
    address: "مازندران - نوشهر - خیابان ساحلی",
    photos: "",
    rate: "4.7",
    discounted_price: null,
    price: 8000000000,
    tags: ["خرید", "ساحلی", "شمال"],
    last_updated: "2026-06-09T10:00:00.000Z",
    capacity: 8,
    location: { lat: 36.6523, lng: 51.4967 },
    categories: "villa",
    bathrooms: 3,
    parking: 2,
    rooms: 4,
    yard_type: "private",
    num_comments: 19,
    discount_id: null,
    transaction_type: "buy",
    sellerId: 305,
    sellerName: "امید کاظمی",
    caption: "ویلای ساحلی با دسترسی مستقیم به دریا در نوشهر",
    bookings: 0,
    favoriteId: 24,
    isFavorite: true,
  },
];

export const GetBuySection = async (): Promise<HousesProps["houses"]> => {
  await new Promise((r) => setTimeout(r, 200));
  return mockBuyHouses;
};