 import { HousesProps } from "@/types";

const mockRentHouses: HousesProps["houses"] = [
  {
    id: 10,
    title: "آپارتمان اجاره‌ای مدرن",
    address: "تهران - سعادت‌آباد - بلوار دریا",
    photos: "",
    rate: "4.3",
    discounted_price: null,
    price: 45000000,
    tags: ["اجاره", "مدرن", "آپارتمان"],
    last_updated: "2026-06-10T10:00:00.000Z",
    capacity: 4,
    location: { lat: 35.7617, lng: 51.3767 },
    categories: "apartment",
    bathrooms: 1,
    parking: 1,
    rooms: 2,
    yard_type: "none",
    num_comments: 5,
    discount_id: null,
    transaction_type: "rent",
    sellerId: 201,
    sellerName: "حسین نجفی",
    caption: "آپارتمانی روشن و مدرن با امکانات کامل در منطقه سعادت‌آباد",
    bookings: 8,
    favoriteId: null,
    isFavorite: false,
  },
  {
    id: 11,
    title: "خانه ویلایی اجاره‌ای",
    address: "کرج - مهرشهر - فاز ۳",
    photos: "",
    rate: "4.6",
    discounted_price: 28000000,
    price: 35000000,
    tags: ["اجاره", "ویلا", "حیاط"],
    last_updated: "2026-06-11T08:00:00.000Z",
    capacity: 6,
    location: { lat: 35.7900, lng: 50.9391 },
    categories: "villa",
    bathrooms: 2,
    parking: 2,
    rooms: 3,
    yard_type: "private",
    num_comments: 11,
    discount_id: 5,
    transaction_type: "rent",
    sellerId: 202,
    sellerName: "زهرا موسوی",
    caption: "خانه ویلایی با حیاط بزرگ و پارکینگ اختصاصی در کرج",
    bookings: 14,
    favoriteId: null,
    isFavorite: false,
  },
  {
    id: 12,
    title: "سوئیت مبله مرکز شهر",
    address: "تهران - انقلاب - خیابان ۱۶ آذر",
    photos: "",
    rate: "4.1",
    discounted_price: null,
    price: 20000000,
    tags: ["اجاره", "مبله", "مرکزی"],
    last_updated: "2026-06-12T14:00:00.000Z",
    capacity: 2,
    location: { lat: 35.7008, lng: 51.3924 },
    categories: "apartment",
    bathrooms: 1,
    parking: 0,
    rooms: 1,
    yard_type: "none",
    num_comments: 3,
    discount_id: null,
    transaction_type: "rent",
    sellerId: 203,
    sellerName: "آرمین شریفی",
    caption: "سوئیت مبله کامل در مرکز تهران، مناسب برای مجردین و دانشجویان",
    bookings: 20,
    favoriteId: 12,
    isFavorite: true,
  },
  {
    id: 13,
    title: "آپارتمان رهن کامل",
    address: "تهران - پونک - بلوار آیت",
    photos: "",
    rate: "4.4",
    discounted_price: null,
    price: 800000000,
    tags: ["رهن", "آپارتمان", "نوساز"],
    last_updated: "2026-06-09T09:00:00.000Z",
    capacity: 5,
    location: { lat: 35.7456, lng: 51.3245 },
    categories: "apartment",
    bathrooms: 2,
    parking: 1,
    rooms: 3,
    yard_type: "none",
    num_comments: 7,
    discount_id: null,
    transaction_type: "mortgage",
    sellerId: 204,
    sellerName: "نیلوفر احمدی",
    caption: "آپارتمان نوساز ۱۲۰ متری با رهن کامل در منطقه پونک",
    bookings: 2,
    favoriteId: null,
    isFavorite: false,
  },
  {
    id: 14,
    title: "آپارتمان دوخوابه اجاره‌ای",
    address: "تهران - شهرک غرب - فلامک شمالی",
    photos: "",
    rate: "4.7",
    discounted_price: 38000000,
    price: 50000000,
    tags: ["اجاره", "دوخوابه", "شهرک غرب"],
    last_updated: "2026-06-13T11:00:00.000Z",
    capacity: 4,
    location: { lat: 35.7672, lng: 51.3543 },
    categories: "apartment",
    bathrooms: 2,
    parking: 1,
    rooms: 2,
    yard_type: "none",
    num_comments: 9,
    discount_id: 6,
    transaction_type: "rent",
    sellerId: 205,
    sellerName: "داریوش پور",
    caption: "آپارتمان دوخوابه نقلی در شهرک غرب با دسترسی عالی به امکانات",
    bookings: 11,
    favoriteId: null,
    isFavorite: false,
  },
];

export const GetRentSection = async (): Promise<HousesProps["houses"]> => {
  await new Promise((r) => setTimeout(r, 200));
  return mockRentHouses;
};