// import type { Metadata } from "next";
// import "./globals.css";
import { Button, Modal } from "@heroui/react";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer";
import HeaderDashboard from "@/components/dashboard/header/HeaderDashboard";
import SideBar from "@/components/dashboard/sideBar/SideBar";
import ModalComponent from "@/components/ui/modal/modalComponent";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="bg-[#ECECEC] w-full h-full flex p-8 gap-3 ">
        <div>
          <SideBar />
        </div>
        <div className="w-full">
          <HeaderDashboard />
          {children}
        </div>
      </div>
    </>
  );
}
