import type { Metadata } from "next";
import "./globals.css";
// import Header from "@/components/common/Header/Header";
// import Footer from "@/components/common/Footer";
import { ThemeProvider } from "next-themes";
import ClientProvider from "@/providers/query-client-provider";
import localFont from "next/font/local"

const iranSans = localFont({
  src:[
    {
      path: "../assets/fonts/iran-sans/IRANSans_UltraLight.ttf",
      weight: "200",
    },
    {
      path: "../assets/fonts/iran-sans/IRANSans_Light.ttf",
      weight: "300",
    },
    {
      path: "../assets/fonts/iran-sans/IRANSans.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/iran-sans/IRANSans_Medium.ttf",
      weight: "500",
    },
    {
      path: "../assets/fonts/iran-sans/IRANSans_Bold.ttf",
      weight: "700",
    },
    {
      path: "../assets/fonts/iran-sans/IRANSans_Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-iran-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      dir="rtl"
      lang="en"
      className={`h-full antialiased`}
    >
      <body className=
      {`${iranSans.className} min-h-full flex flex-col justify-center items-center overflow-x-hidden`}>
        <ClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={false}
            storageKey="my-theme"
          >
            {/* <Header /> */}
            {children}
            {/* <Footer /> */}
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
